spring.application.name=student

#Postgresql configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/gunay
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update

server.port=8081

